// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPFWRBLdBNiod4N8zgv2maTvVmIpqwvb4',
    appId: '1:745999500440:web:a5e42cfd8cbe442335fced',
    messagingSenderId: '745999500440',
    projectId: 'watch-list-flutter',
    authDomain: 'watch-list-flutter.firebaseapp.com',
    storageBucket: 'watch-list-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByb7TqyHQXG69uEVMdQ_MIyjcQIbOqiI0',
    appId: '1:745999500440:android:90915608d12285c435fced',
    messagingSenderId: '745999500440',
    projectId: 'watch-list-flutter',
    storageBucket: 'watch-list-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDePXKyhJZYkwxp2OZwDj37SYQSnYF8Bfg',
    appId: '1:745999500440:ios:a82884b4ddbe58ca35fced',
    messagingSenderId: '745999500440',
    projectId: 'watch-list-flutter',
    storageBucket: 'watch-list-flutter.appspot.com',
    iosClientId: '745999500440-fnma9rbjgrjlkkia239shbeoutjs264k.apps.googleusercontent.com',
    iosBundleId: 'com.example.watchList',
  );
}
